<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.1</Version>
        <PackAsTool>true</PackAsTool>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <ToolCommandName>cli-guid-generate</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <RootNamespace>GuidGenerator</RootNamespace>
        <RepositoryUrl>https://github.com/JamesLoyd/CLIGuidGeneratorTool</RepositoryUrl>
        <Authors>James Loyd</Authors>
        <Description>CLI tool for generating GUIDs</Description>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath="\"/>
        <None Include="LICENSE" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
